services:
  - type: web
    name: django-chat-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate
    startCommand: gunicorn chattingapp.wsgi:application
    envVars:
      - key: DATABASE_URL
        scope: all
      - key: SECRET_KEY
        scope: all
      - key: DEBUG
        value: false
        scope: all
      - key: ALLOWED_HOSTS
        value: "*"
        scope: all
